services:
  db:
    container_name: mongo
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    volumes:
      - mongo_data:/data/db
    networks:
      - default
      
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000" 
    environment:
      - MONGO_URI=mongodb://db:27017/credit_database
    depends_on:
      - db
    networks:
      - default

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - default
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  default:
    driver: bridge