version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/credit_database
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - backend

  mongo:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge